# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mostly on Ai
#email: dejan.batanjac@gmail.com
description: Learning tools and examples for the Ai world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dejanbatanjac.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# mathjax: true
math_engine: katex
